"""add created column

Revision ID: cab653d3f886
Revises: fc8715ec7b4a
Create Date: 2021-07-13 14:37:25.437190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab653d3f886'
down_revision = 'fc8715ec7b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'created')
    # ### end Alembic commands ###
